config/routes.rb
Uploader::Application.routes.draw do

  resources :images
  resources :images do
    member do
      get 'show_image'
    end
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :file, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.limit(10)
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    upload_file = image_params[:file]
    image = {}
    if upload_file != nil
      image[:filename] = upload_file.original_filename
      image[:file] = upload_file.read
    end
    @image = Image.new(image)
    if @image.save
      flash[:success] = "画像を保存しました。"
      redirect_to @image
    else
      flash[:error] = "画像を保存できませんでした。"
    end
  end

  def show_image
    @image = Image.find(params[:id])
    send_data @image.file, :type => 'image/jpeg', :disposition => 'inline'
  end 

  private

    def image_params
      params.require(:image).permit(
        :filename,:file
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/index.html.erb
<% @images.each do |image| %>
<%= image_tag show_image_image_path(image), class: "middle-img" %>
<% end %>

app/views/images/new.html.erb
<%= form_for(@image) do |f| %>
  <%= f.file_field :file,accept: "image/*" %>
  <%= f.submit "Upload" %>
<% end %>

app/views/images/show.html.erb
<%= image_tag show_image_image_path(@image),class: "large-img" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
<%= yield %>

</body>
</html>